### ISSUE TITLE
bug: source file and html are out of sync

### ISSUE THREAD

**Issue by BuptStEve** [BuptStEve/markdown-it-vuese#3]
**Version**
Version 0.2.2

**Describe the bug**
After modifying the source file, the content of the page does not refresh.

**The temporary solution is to save the corresponding markdown file.**

**To Reproduce**
1. use it with vuepress
2. run `vuepress dev`
3. modify source file, like `foo.vue`, and save it
4. out of sync

**Expected behavior**
After modifying the source file, we should get a new content.

**Additional context**
It's the same problem with [Import Code Snippets](https://vuepress.vuejs.org/guide/markdown.html#import-code-snippets)

https://github.com/vuejs/vuepress/issues/1309

**Comment by shigma** [comment]
You can try `env.loader.addDependency`, it will be a new API invented by vuepress v1.0.0-alpha.40.

[PR](https://github.com/vuejs/vuepress/pull/1337)

**Comment by BuptStEve** [comment]
> You can try `env.loader.addDependency`, it will be a new API invented by vuepress v1.0.0-alpha.40.
> 
> [PR](https://github.com/vuejs/vuepress/pull/1337)

Good job!
